### ISSUE TITLE
Prestige (summary page wording)

### ISSUE THREAD

**Issue by kevin4567** [minotauri/CFB-Coach#15]
I don't know if this is similar to my previous issue post, but prestige is weird in the career mode. You can win a rivalry game and gain 0 prestige, then win a few years later and gain 2. However this prestige never gets added to your total prestige. Also Prestige won't save from years sometimes, you can have a 47 one year and gain 0 prestige but have 45 the next season. Thanks for the apk!

**Comment by minotauri** [comment]
It's not a bug, but I do need to update the summary page. I recently added player disciplinary actions mid-season. The result of how these actions result will add/subtract prestige from the team and the coach rating mid-season, but the summary page does not account for it. I keep forgetting to implement that into the summary, so thanks for pointing that out for me. The News does cover this though, but also does not list the amount of prestige lost/gained.

**Comment by minotauri** [comment]
Upon re-reviewing this, this isn't a bug, its actually correct but depends on how you read the summary page. I will attempt the wording in an update

**Comment by kevin4567** [comment]
Thanks, I kinda got the gist of that after a while. I kinda rushed into things.
