### ISSUE TITLE
Winning championships

### ISSUE THREAD

**Issue by kevin4567** [minotauri/CFB-Coach#25]
Some years you can go undefeated and win the championship and also have a team bonding for prestige but still deduct from your overall prestige. Idk if that was intentional or not, just seemed a bit weird.

**Comment by minotauri** [comment]
I'll look into it. Thanks for the comment. The only way I think this could happen is if your overall conference does terrible that year. I put in a prestige limiter based on the conference quality. Each conference has a min/max prestige that their teams can reach based on the average of each team's prestige at the beginning of that season. It makes it very hard for an average team in a bad conference to just go undefeated and jump to the top tier prestige in a few seasons which was happening with Mt West and Conf USA teams frequently before.

**Comment by minotauri** [comment]
I did change this in one of the more recent updates.
