### ISSUE TITLE
Crash at graduation

### ISSUE THREAD

**Issue by foxe2** [minotauri/CFB-Coach#31]
Running on the most recent version of Android.

I'm playing career mode and when I get to Graduation phase, if I scroll at all the game automatically crashes.

**Comment by minotauri** [comment]
Hmm that is a strange one. There was an old bug related to this phase but I fixed it by not allowing you to view your roster/depth chart. Is this repeating for you? I havent seen it occur yet, which is why I ask.

**Comment by foxe2** [comment]
Yeah, I noticed I could skip it if I didn't scroll through whatever menu I was open, at all, but i repeated the process multiple times and it crashed every time, sometimes even when I wouldn't scroll.

**Comment by minotauri** [comment]
I still havent encountered this bug yet. Let me know if you still get it in any of my newest versions.

**Comment by foxe2** [comment]
Newest version. I'm on a galaxy s7. Start a new career in Challenge mode, play through as normal, make it to offseason. Keep going and once you click the "play week: graduation" the app should crash

**Comment by foxe2** [comment]
I will admit that it doesn't happen EVERY time, but of the 3 times I tried it, it happened twice. I am not sure exactly what I did to make it not crash the third time I tried it

**Comment by foxe2** [comment]
It happened in dynasty mode as well. Play through a season and then click "offseason: graduation" and if you try to scroll at all while its loading, it will crash

**Comment by minotauri** [comment]
Does this still occur on any of the latest versions?

**Comment by foxe2** [comment]
Hi there-

Yes, unfortunately this problem still happens. Since I noticed you made it so that the roster can't be accessed in the offseason, allow me to run through the steps I go through in order to best detail the problem.  I did this three times, just to make sure I had the order correct (version 2.00 BETA: 01-14-2018):

1. New career, challenge mode.
2. Play through entire season, advance to offseason.
3. Advance through offseason phases until I get to the prompt to advance with "Off-season: Graduation"
4. I start to be more careful here. Advance one more time to the "Transfer Players" phase.
5. Attempt to scroll on whatever screen I'm on.  The first two times I was looking at the schedule when the phase started.  As long as I don't scroll anywhere, the app will not crash and I can continue to the next phase no problem.  However, if I even so much as scroll a single pixel, the app will freeze up and crash after a second or two.  I noticed that if I was on this screen and I DID NOT SCROLL at all, I could select a different view to look at (News, stats, etc.) and I could scroll through these fine, and advance whenever I wanted.  And if I clicked back to the schedule, it would be totally blank and "Scrolling" on this screen did not crash the app.  But I could still, at this point, continue to the next phase perfectly fine.

As a fellow programmer, I get how frustrating these minute bugs can be.  If I can be of any more assistance, please let me know.  I've really been looking forward to trying this app but these kind of game-breaking bugs only frustrate me and so I haven't had the chance to fully experience the game yet.

**Comment by minotauri** [comment]
Hi,

Thanks for the info and sorry this is frustrating. I think I found out the issue. The game resets (advances all the stats at Graduation) including Schedule. So if you're on a schedule page and you scroll, it's probably trying to pull data that doesnt exist anymore. I think I'll have to either block users from accessing it and drop you to another screen or something.

Thanks

**Comment by minotauri** [comment]
I put up a new file that has a temp fix until I come up with a more robust solution. It forces you back to the Stats page which doesnt crash. Ill see if I can find out a more robust and useful fix for this in the future.

**Comment by foxe2** [comment]
Great! The game no longer crashes for me.  Thanks for developing a workaround!
